services:
  caddy:
    image: caddy:latest
    container_name: sushi_rol
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/usr/share/caddy
      - caddy_data:/data
volumes:
  caddy_data: