services:
  caddy:
    image: caddy:latest
    container_name: sushi_rol
    ports:
      - "8800:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - ./site:/usr/share/caddy:Z
      - caddy_data:/data
volumes:
  caddy_data:
